---
title: "R Notebook"
output: html_notebook
---

```{r packages}
library(MASS)
library(locpol)
library(functClust)
library(lpridge)
library(lokern)
library(KernSmooth)
library(locfit)
library(stats)
source("functions.R")
```

```{r parameters that we can compare}
K <- 10                             #Number of folds
d <- 2                              #Degree
h <- 0.5                            #Bandwidth
N <- 1000                        #Sizes of sample

Samples_sizes <- 10^(1:3); s <- length(Samples_sizes) #length(xeval) < 5000 in locpol that's why 3 here atm
time_locpol <- 1:s*0
time_locfit <- 1:s*0
time_locpoly <- 1:s*0
time_ksmooth <- 1:s*0

df_results <- data.frame(Samples_sizes,time_locpol,time_locfit,time_locpoly,time_ksmooth) #Dataframe to fill

#ind <- matrix(sample(1:N),ncol=K)   #Pipeline for dividing the sample
```

```{r Time comparison}
t <- c(0,0,0)
i <- 1
for (n in df_results$Samples_sizes){
  set.seed(1)
  X <- 0:n/(n/5)  #To go from 0 to 5
  Y <- dmixnorm(X,mu1 = 4)
  Y_noisy <- Noise_induction(Y,sig_gauss = abs(max(Y)-min(Y))/10)
  
  t[1] <- Sys.time()
  y_locpol <- locpol(Y_noisy~X,data.frame(X,Y_noisy),bw = h,deg = d,kernel = gaussK,xeval = X)  #xeval has to be < 5000....
  t[1] <- Sys.time()-t[1]
  
  t[2] <- Sys.time()
  y_locpoly <- locpoly(X,Y_noisy, bandwidth=h, degree=d,gridsize = N) 
  t[2] <- Sys.time()-t[2]
  
  t[3] <- Sys.time()
  y_locfit <- locfit(X~lp(Y_noisy,h=h/2,deg=d),data.frame(X,Y_noisy), kern = 'gauss') #TODO: check if bandwidth has indeed to be treated like that
  t[3] <- Sys.time()-t[3]
  
  t[4] <- Sys.time()  
  y_ksmooth <- ksmooth(X,Y_noisy, bandwidth=h, kernel = "normal",X) #NO DEGREE
  t[4] <- Sys.time() - t[4]
  
  df_results[i,-1] <- t
  print(i)
  i <- i+1
  
  
  
}
```
```{r}
#Plotting locpol 
#lines(y_locpol[["lpFit"]][["X"]],y_locpol[["lpFit"]][["Y_noisy"]],col = "red")
```







