---
title: "functions_build"
output: html_document
date: "2022-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
piecewise linear function
c1 are the vector of thresholds
c2, c3 are the coefficients, must have length =c1 +1

```{r}
piece_linear <- function(x, c1, c2, c3, noise=1){
  #c1 are the thresholds, c2 are the coefficients, c3 are the added terms
  y <- rep(0, length(x))

  for (i in seq(1, length(c1) +1)){
    if (i==1){y[x < c1[i]] = c2[i]*(x[x<c1[i]]) + c3[i]}
    else if (i == length(c1)+1){y[x >= c1[i-1]] = c2[i]*(x[x>=c1[i-1]]) + c3[i]}
    else{y[(x < c1[i]) & (x>=c1[i-1])] = c2[i]*(x[(x < c1[i]) & (x>=c1[i-1])]) + c3[i]}
  }
  
  y <- y + rnorm(length(x), 0, noise)
  
  return(y)
}
```
sin(1/x) ish, for nonderavative
```{r}
sinx_1 <- function(x, a, noise=1){
  y <- sin(a/x)*(sqrt(x))
  y <- y + rnorm(length(x), 0, noise)
  
  return(y)
}
```
weiertrass' resembles
b must be odd integer
0<a< 1
ab > 1 +3/2 * pi, or >7 for sure 
```{r}
weiertrass <- function(x, a=0.9, b=9){
  y <- rep(0, length(x))
  for (i in seq(0, 200)){
    y = y + (a^i)*cos(pi*x*(b^i))
  }
  return(y)
}

```
